server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  #配置zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.springcloud.entities
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    #表示把自己注册到EurekaServer中，默认是true
    register-with-eureka: true
    #是否从EurekaServer抓取已经存在的注册信息，默认是true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1  #像服务端发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 2 #
